---
- hosts: all
  tasks:
    - name: Install nginx
      sudo: yes
      apt: name=nginx state=latest update_cache=yes

    - name: Install common soft
      sudo: yes
      apt: name={{item}} state=latest update_cache=yes
      with_items:
          - git
          - python-dev
          - tmux
          - grc
          - vim
          - vim-nox

    - name: Dots | Clone dots
      git: repo=https://github.com/StyleEX/dots.git accept_hostkey=yes dest=~/dots recursive=no

    - name: Dots | Install vundle
      git: repo=https://github.com/gmarik/vundle.git dest=~/.vim/bundle/vundle

    - name: Dots | Link dots
      file: src={{item.src}} dest={{item.dest}} state=link
      with_items:
          - { src: '~/dots/dots/mysql/.my.cnf', dest: '~/.my.cnf' } 
          - { src: '~/dots/dots/grc/.grcat', dest: '~/.grcat' } 
          - { src: '~/dots/dots/git/.gitconfig', dest: '~/.gitconfig' } 
          - { src: '~/dots/dots/vim/.vimrc', dest: '~/.vimrc' } 
          - { src: '~/dots/dots/bash/.bashrc', dest: '~/.bashrc' } 
          - { src: '~/dots/dots/tmux/.tmux.conf', dest: '~/.tmux.conf' } 

    - name: Dots | Install vim plugins
      command: vim +PluginInstall +qall
